package com.linktic.dupis;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SolicitudDupis implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "SOLICITUDDUPIS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "SOLICITUDDUPIS_ID_SEQ", name = "SOLICITUDDUPIS_ID_GENERATOR")
    private java.lang.Long id;

    public SolicitudDupis() {
    }
    
    public SolicitudDupis(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}